/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ferna
 */
public class CadastroReceitas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroReceitas
     */
    public CadastroReceitas() {
        initComponents();
        //CarregarTabela();
        DesabilitarJbuttom();
        DesabilitarJTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void LimparjTextField(){
        jTextFieldDataRecebimento.setText("");
        jTextFieldDescricaoReceita.setText("");
        jTextFieldIdConta.setText("");
        jTextFieldTipoReceita.setText("");
        jTextFieldVlrValor.setText("");
        jTextFieldsDataRecebimentoEsperado.setText("");
    }
    
    
    public void DesabilitarJbuttom(){
        jButtonAtualizarReceita.setEnabled(false);
        jButtonCadastrarReceita.setEnabled(false);
        jButtonExcluirReceita.setEnabled(false);
    }
    
    public void DesabilitarJTextField(){
        jTextFieldDataRecebimento.setEnabled(false);
        jTextFieldDescricaoReceita.setEnabled(false);
        jTextFieldIdConta.setEnabled(false);
        jTextFieldTipoReceita.setEnabled(false);
        jTextFieldVlrValor.setEnabled(false);
        jTextFieldsDataRecebimentoEsperado.setEnabled(false);
        
        jLabelDataRecebimento.setEnabled(false);
        jLabelDataRecebimentoEsperado.setEnabled(false);
        jLabelDescricaoReceita.setEnabled(false);
        jLabelIdConta.setEnabled(false);
        jLabelTipoReceita.setEnabled(false);
        jLabelVlrReceita.setEnabled(false);        
    }
    
    public void HabilitarJbuttom(){
        jButtonAtualizarReceita.setEnabled(true);
        jButtonCadastrarReceita.setEnabled(true);
        jButtonExcluirReceita.setEnabled(true);
    }
    
    public void HabilitarJTextField(){
        jTextFieldDataRecebimento.setEnabled(true);
        jTextFieldDescricaoReceita.setEnabled(true);
        jTextFieldIdConta.setEnabled(true);
        jTextFieldTipoReceita.setEnabled(true);
        jTextFieldVlrValor.setEnabled(true);
        jTextFieldsDataRecebimentoEsperado.setEnabled(true);
        
        jLabelDataRecebimento.setEnabled(true);
        jLabelDataRecebimentoEsperado.setEnabled(true);
        jLabelDescricaoReceita.setEnabled(true);
        jLabelIdConta.setEnabled(true);
        jLabelTipoReceita.setEnabled(true);
        jLabelVlrReceita.setEnabled(true); 

    }    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastrarReceita = new javax.swing.JButton();
        jButtonExcluirReceita = new javax.swing.JButton();
        jButtonAtualizarReceita = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelIdConta = new javax.swing.JLabel();
        jLabelTipoReceita = new javax.swing.JLabel();
        jLabelDataRecebimento = new javax.swing.JLabel();
        jLabelDataRecebimentoEsperado = new javax.swing.JLabel();
        jLabelDescricaoReceita = new javax.swing.JLabel();
        jLabelVlrReceita = new javax.swing.JLabel();
        jTextFieldIdConta = new javax.swing.JTextField();
        jTextFieldTipoReceita = new javax.swing.JTextField();
        jTextFieldDataRecebimento = new javax.swing.JTextField();
        jTextFieldsDataRecebimentoEsperado = new javax.swing.JTextField();
        jTextFieldDescricaoReceita = new javax.swing.JTextField();
        jTextFieldVlrValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReceitas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição / Criação de Receitas"));

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/novo.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCadastrarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        jButtonCadastrarReceita.setText("Salvar");

        jButtonExcluirReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir.png"))); // NOI18N
        jButtonExcluirReceita.setText("Excluir");

        jButtonAtualizarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        jButtonAtualizarReceita.setText("Atualizar");

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jButtonHome.setText("Home");

        jLabelIdConta.setText("Id Conta");

        jLabelTipoReceita.setText("Tipo");

        jLabelDataRecebimento.setText("Recebimento");

        jLabelDataRecebimentoEsperado.setText("Rec Esperado");

        jLabelDescricaoReceita.setText("Descrição");

        jLabelVlrReceita.setText("Valor");

        jTextFieldIdConta.setText("jTextField1");

        jTextFieldTipoReceita.setText("jTextField2");

        jTextFieldDataRecebimento.setText("jTextField3");

        jTextFieldsDataRecebimentoEsperado.setText("jTextField4");

        jTextFieldDescricaoReceita.setText("jTextField5");

        jTextFieldVlrValor.setText("jTextField6");

        jTableReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Conta", "Tipo", "Recebimento", "Rec Esperado", "Descrição", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTableReceitas);

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovo)
                            .addComponent(jLabelIdConta)
                            .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrarReceita)
                            .addComponent(jLabelTipoReceita)
                            .addComponent(jTextFieldTipoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExcluirReceita)
                            .addComponent(jLabelDataRecebimento)
                            .addComponent(jTextFieldDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAtualizarReceita)
                            .addComponent(jLabelDataRecebimentoEsperado)
                            .addComponent(jTextFieldsDataRecebimentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricaoReceita)
                            .addComponent(jTextFieldDescricaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVlrReceita)
                            .addComponent(jTextFieldVlrValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonCadastrarReceita)
                    .addComponent(jButtonExcluirReceita)
                    .addComponent(jButtonAtualizarReceita)
                    .addComponent(jButtonHome))
                .addGap(18, 18, 18)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdConta)
                    .addComponent(jLabelTipoReceita)
                    .addComponent(jLabelDataRecebimento)
                    .addComponent(jLabelDataRecebimentoEsperado)
                    .addComponent(jLabelDescricaoReceita)
                    .addComponent(jLabelVlrReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsDataRecebimentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescricaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVlrValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        HabilitarJTextField();
        DesabilitarJbuttom();
        jButtonCadastrarReceita.setEnabled(true);
        LimparjTextField();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarReceita;
    private javax.swing.JButton jButtonCadastrarReceita;
    private javax.swing.JButton jButtonExcluirReceita;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabelDataRecebimento;
    private javax.swing.JLabel jLabelDataRecebimentoEsperado;
    private javax.swing.JLabel jLabelDescricaoReceita;
    private javax.swing.JLabel jLabelIdConta;
    private javax.swing.JLabel jLabelTipoReceita;
    private javax.swing.JLabel jLabelVlrReceita;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReceitas;
    private javax.swing.JTextField jTextFieldDataRecebimento;
    private javax.swing.JTextField jTextFieldDescricaoReceita;
    private javax.swing.JTextField jTextFieldIdConta;
    private javax.swing.JTextField jTextFieldTipoReceita;
    private javax.swing.JTextField jTextFieldVlrValor;
    private javax.swing.JTextField jTextFieldsDataRecebimentoEsperado;
    // End of variables declaration//GEN-END:variables
}
