/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Conta;
import Controller.Conexao;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Fernando Marcos Rodrigues
 * Tela Edição de Contas
 */
public class CadastroConta extends javax.swing.JFrame {

    /**
     * Creates new form CadastroConta
     */
    public CadastroConta() {
        initComponents();
        CarregarTabela();
        DesabilitarJbuttom();
        DesabilitarJTextField();
        LimparjTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonNovaConta = new javax.swing.JButton();
        jButtonAtualizarContas = new javax.swing.JButton();
        jButtonExcluirContas = new javax.swing.JButton();
        jLabelIdConta = new javax.swing.JLabel();
        jLabelTipoConta = new javax.swing.JLabel();
        jLabelInstFinanceira = new javax.swing.JLabel();
        jLabelVlrSaldo = new javax.swing.JLabel();
        jTextFieldIdConta = new javax.swing.JTextField();
        jTextFieldTipoConta = new javax.swing.JTextField();
        jTextFieldInstFinanceira = new javax.swing.JTextField();
        jTextFieldVlrSaldo = new javax.swing.JTextField();
        jButtonCadastrarConta = new javax.swing.JButton();
        jScrollPaneContas = new javax.swing.JScrollPane();
        jTableContas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas");

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição / Criação de Contas"));

        jButtonNovaConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/novo.png"))); // NOI18N
        jButtonNovaConta.setText("Novo");
        jButtonNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaContaActionPerformed(evt);
            }
        });

        jButtonAtualizarContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        jButtonAtualizarContas.setText("Modificar");
        jButtonAtualizarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarContasActionPerformed(evt);
            }
        });

        jButtonExcluirContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir.png"))); // NOI18N
        jButtonExcluirContas.setText("Excluir");
        jButtonExcluirContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirContasActionPerformed(evt);
            }
        });

        jLabelIdConta.setText("Id Conta");

        jLabelTipoConta.setText("Tipo Conta");

        jLabelInstFinanceira.setText("Instituição");

        jLabelVlrSaldo.setText("Saldo");

        jTextFieldIdConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdContaActionPerformed(evt);
            }
        });

        jTextFieldTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoContaActionPerformed(evt);
            }
        });

        jButtonCadastrarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        jButtonCadastrarConta.setText("Salvar");
        jButtonCadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarContaActionPerformed(evt);
            }
        });

        jTableContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodConta", "TipoConta", "Instituição", "Saldo"
            }
        ));
        jTableContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableContasMouseClicked(evt);
            }
        });
        jScrollPaneContas.setViewportView(jTableContas);

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("*Selecione na tabela abaixo a conta para Exclusão ou Alteração");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.setActionCommand("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelBaseLayout.createSequentialGroup()
                                .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInstFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelInstFinanceira))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVlrSaldo)
                                    .addComponent(jTextFieldVlrSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneContas, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBaseLayout.createSequentialGroup()
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNovaConta)
                                    .addComponent(jLabelIdConta))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCadastrarConta)
                                    .addComponent(jLabelTipoConta))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluirContas)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAtualizarContas)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarConta)
                    .addComponent(jButtonExcluirContas)
                    .addComponent(jButtonAtualizarContas)
                    .addComponent(jButtonNovaConta)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoConta)
                    .addComponent(jLabelIdConta)
                    .addComponent(jLabelInstFinanceira)
                    .addComponent(jLabelVlrSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInstFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVlrSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jScrollPaneContas, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarContaActionPerformed
        
        Conta conta = new Conta();
        conta.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        conta.setInstFinanceira(jTextFieldInstFinanceira.getText());
        conta.setTipoConta(jTextFieldTipoConta.getText());
        conta.setVlrSaldo(Double.parseDouble(jTextFieldVlrSaldo.getText()));
        conta.cadastrarConta(conta);
        CarregarTabela();
        LimparjTextField();
    }//GEN-LAST:event_jButtonCadastrarContaActionPerformed

    private void jTextFieldTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoContaActionPerformed

    private void jTextFieldIdContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdContaActionPerformed

    private void jTableContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContasMouseClicked
        
        Conta contas = new Conta();
        Integer index = jTableContas.getSelectedRow();
        contas= contas.listarContas().get(index);
        jTextFieldIdConta.setText(String.valueOf(contas.getIdConta()));
        jTextFieldTipoConta.setText(contas.getTipoConta());
        jTextFieldInstFinanceira.setText(contas.getInstFinanceira());
        jTextFieldVlrSaldo.setText(String.valueOf(contas.getVlrSaldo())); 
        
        jButtonCadastrarConta.setEnabled(false);
        jButtonAtualizarContas.setEnabled(true);
        jButtonExcluirContas.setEnabled(true);
        HabilitarJTextField();
        jLabelIdConta.setEnabled(false);
        jTextFieldIdConta.setEnabled(false);        
    }//GEN-LAST:event_jTableContasMouseClicked

    private void jButtonAtualizarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarContasActionPerformed
            
        Conta contas =new Conta();        
        Integer index = jTableContas.getSelectedRow();
        
        contas = contas.listarContas().get(index);
        contas.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        contas.setTipoConta(jTextFieldTipoConta.getText());
        contas.setInstFinanceira(jTextFieldInstFinanceira.getText());
        contas.setVlrSaldo(Double.parseDouble(jTextFieldVlrSaldo.getText()));
        
        contas.editarConta(contas);    
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonAtualizarContasActionPerformed

    private void jButtonExcluirContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirContasActionPerformed
        
        Conta contas =new Conta();        
        Integer index = jTableContas.getSelectedRow();
        contas = contas.listarContas().get(index);
        contas.removerConta(Integer.parseInt(jTextFieldIdConta.getText()));
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonExcluirContasActionPerformed

    private void jButtonNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaContaActionPerformed
       
        HabilitarJTextField();
        DesabilitarJbuttom();
        jButtonCadastrarConta.setEnabled(true);
        LimparjTextField();        
    }//GEN-LAST:event_jButtonNovaContaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Principal telaPrincipal = new Principal();
            telaPrincipal.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        } 
        finally{
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LimparjTextField(){
        jTextFieldIdConta.setText("");
        jTextFieldTipoConta.setText("");
        jTextFieldInstFinanceira.setText("");
        jTextFieldVlrSaldo.setText("");
    }
    
    
    private void CarregarTabela(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableContas.getModel();
        tabela.setNumRows(0);
      
        Conta contas = new Conta();
        
        try {
            for(Conta c: contas.listarContas()){
                tabela.addRow(new Object[]{
                    c.getIdConta(),
                    c.getTipoConta(),
                    c.getInstFinanceira(),
                    c.getVlrSaldo()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }
    public void DesabilitarJbuttom(){
        jButtonAtualizarContas.setEnabled(false);
        jButtonCadastrarConta.setEnabled(false);
        jButtonExcluirContas.setEnabled(false);
    }
    
    public void DesabilitarJTextField(){
        jTextFieldIdConta.setEnabled(false);
        jTextFieldInstFinanceira.setEnabled(false);
        jTextFieldTipoConta.setEnabled(false);
        jTextFieldVlrSaldo.setEnabled(false);
        jLabelIdConta.setEnabled(false);
        jLabelTipoConta.setEnabled(false);
        jLabelInstFinanceira.setEnabled(false);
        jLabelVlrSaldo.setEnabled(false);
    }
    
    public void HabilitarJbuttom(){
        jButtonAtualizarContas.setEnabled(true);
        jButtonCadastrarConta.setEnabled(true);
        jButtonExcluirContas.setEnabled(true);
    }
    
    public void HabilitarJTextField(){
        jTextFieldIdConta.setEnabled(true);
        jTextFieldInstFinanceira.setEnabled(true);
        jTextFieldTipoConta.setEnabled(true);
        jTextFieldVlrSaldo.setEnabled(true);
        jLabelIdConta.setEnabled(true);
        jLabelTipoConta.setEnabled(true);
        jLabelInstFinanceira.setEnabled(true);
        jLabelVlrSaldo.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizarContas;
    private javax.swing.JButton jButtonCadastrarConta;
    private javax.swing.JButton jButtonExcluirContas;
    private javax.swing.JButton jButtonNovaConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIdConta;
    private javax.swing.JLabel jLabelInstFinanceira;
    private javax.swing.JLabel jLabelTipoConta;
    private javax.swing.JLabel jLabelVlrSaldo;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPaneContas;
    private javax.swing.JTable jTableContas;
    private javax.swing.JTextField jTextFieldIdConta;
    private javax.swing.JTextField jTextFieldInstFinanceira;
    private javax.swing.JTextField jTextFieldTipoConta;
    private javax.swing.JTextField jTextFieldVlrSaldo;
    // End of variables declaration//GEN-END:variables
}
