/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pubfuture.Despesa;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
import pubfuture.Conta;

/**
 *
 * @author ferna
 */
public class cadastroDespesa extends javax.swing.JFrame {

    /**
     * Creates new form cadastroDespesa
     */
    public cadastroDespesa() {
        initComponents();
        CarregarTabela();
        DesabilitarJbuttom();
        DesabilitarJTextField();
        LimparjTextField();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonNovaDespesa = new javax.swing.JButton();
        jButtonCadastrarDespesas = new javax.swing.JButton();
        jButtonExcluirDespesas = new javax.swing.JButton();
        jButtonAtualizarDespesas = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelIdConta = new javax.swing.JLabel();
        jLabelDataPagamento = new javax.swing.JLabel();
        jLabelDataPagamentoEsperado = new javax.swing.JLabel();
        jLabelTipoDespesa = new javax.swing.JLabel();
        jLabelvalor = new javax.swing.JLabel();
        jTextFieldIdConta = new javax.swing.JTextField();
        jTextFieldDataPagamento = new javax.swing.JTextField();
        jTextFieldDataPagamentoEsperado = new javax.swing.JTextField();
        jTextFieldTipoDespesa = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDespesas = new javax.swing.JTable();
        jLabelInstrucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição / Criação de Despesas"));

        jButtonNovaDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/novo.png"))); // NOI18N
        jButtonNovaDespesa.setText("Novo");
        jButtonNovaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaDespesaActionPerformed(evt);
            }
        });

        jButtonCadastrarDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        jButtonCadastrarDespesas.setText("Salvar");
        jButtonCadastrarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarDespesasActionPerformed(evt);
            }
        });

        jButtonExcluirDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir.png"))); // NOI18N
        jButtonExcluirDespesas.setText("Excluir");
        jButtonExcluirDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirDespesasActionPerformed(evt);
            }
        });

        jButtonAtualizarDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        jButtonAtualizarDespesas.setText("Atualizar");
        jButtonAtualizarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarDespesasActionPerformed(evt);
            }
        });

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabelIdConta.setText("Ad Conta");

        jLabelDataPagamento.setText("Pagamento");

        jLabelDataPagamentoEsperado.setText("Pgto Esperado");

        jLabelTipoDespesa.setText("Tipo Despesa");

        jLabelvalor.setText("Valor");

        jTextFieldIdConta.setText("jTextField1");

        jTextFieldDataPagamento.setText("jTextField2");

        jTextFieldDataPagamentoEsperado.setText("jTextField3");
        jTextFieldDataPagamentoEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataPagamentoEsperadoActionPerformed(evt);
            }
        });

        jTextFieldTipoDespesa.setText("jTextField4");

        jTextFieldValor.setText("jTextField5");

        jTableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Conta", "Data Pgto", "Data Pgto Esperado", "Tipo", "valor"
            }
        ));
        jTableDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDespesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDespesas);

        jLabelInstrucao.setForeground(new java.awt.Color(255, 51, 51));
        jLabelInstrucao.setText("*Selecione na tabela abaixo a Despesa para Exclusão ou Alteração");

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInstrucao)
                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanelBaseLayout.createSequentialGroup()
                            .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonNovaDespesa)
                                .addComponent(jLabelIdConta)
                                .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelBaseLayout.createSequentialGroup()
                                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCadastrarDespesas)
                                        .addComponent(jTextFieldDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonExcluirDespesas)
                                        .addComponent(jLabelDataPagamentoEsperado)
                                        .addComponent(jTextFieldDataPagamentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabelDataPagamento))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTipoDespesa)
                                .addGroup(jPanelBaseLayout.createSequentialGroup()
                                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonAtualizarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTipoDespesa))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelvalor)
                                        .addComponent(jButtonHome)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaDespesa)
                    .addComponent(jButtonCadastrarDespesas)
                    .addComponent(jButtonExcluirDespesas)
                    .addComponent(jButtonAtualizarDespesas)
                    .addComponent(jButtonHome))
                .addGap(12, 12, 12)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataPagamentoEsperado)
                    .addComponent(jLabelIdConta)
                    .addComponent(jLabelDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoDespesa)
                    .addComponent(jLabelvalor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataPagamentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelInstrucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDespesasMouseClicked

        Despesa despesas = new Despesa();
        Integer index = jTableDespesas.getSelectedRow();
        despesas= despesas.listarDespesa().get(index);
        jTextFieldIdConta.setText(String.valueOf(despesas.getIdConta()));
        jTextFieldDataPagamento.setText(String.valueOf(despesas.getDataPagto()));
        jTextFieldDataPagamentoEsperado.setText(String.valueOf(despesas.getDataPagtoEsperado()));
        jTextFieldTipoDespesa.setText(despesas.getTipoDespesa());
        jTextFieldValor.setText(String.valueOf(despesas.getVlrDespesa()));

        jButtonCadastrarDespesas.setEnabled(false);
        jButtonAtualizarDespesas.setEnabled(true);
        jButtonExcluirDespesas.setEnabled(true);
        HabilitarJTextField();
        jLabelIdConta.setEnabled(false);
        jTextFieldIdConta.setEnabled(false);
    }//GEN-LAST:event_jTableDespesasMouseClicked

    private void jTextFieldDataPagamentoEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataPagamentoEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataPagamentoEsperadoActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        try {
            Principal telaPrincipal = new Principal();
            telaPrincipal.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            dispose();
        }

    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAtualizarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDespesasActionPerformed

        Despesa despesas =new Despesa();
        Integer index = jTableDespesas.getSelectedRow();
        despesas = despesas.listarDespesa().get(index);
        despesas.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        despesas.setDataPagto(Date.valueOf(jTextFieldDataPagamento.getText()));
        despesas.setDataPagtoEsperado(Date.valueOf(jTextFieldDataPagamentoEsperado.getText()));
        despesas.setTipoDespesa(jTextFieldTipoDespesa.getText());
        despesas.setVlrDespesa(Double.parseDouble(jTextFieldValor.getText()));

        despesas.editarDespesa(despesas);
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonAtualizarDespesasActionPerformed

    private void jButtonExcluirDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirDespesasActionPerformed
        Despesa despesas =new Despesa();
        Integer index = jTableDespesas.getSelectedRow();
        despesas = despesas.listarDespesa().get(index);
        despesas.removerDespesa(Integer.parseInt(jTextFieldIdConta.getText()));
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonExcluirDespesasActionPerformed

    private void jButtonCadastrarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarDespesasActionPerformed

        Despesa despesa = new Despesa();
        despesa.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        despesa.setDataPagto(Date.valueOf(jTextFieldDataPagamento.getText()));
        despesa.setDataPagtoEsperado(Date.valueOf(jTextFieldDataPagamentoEsperado.getText()));
        despesa.setTipoDespesa(jTextFieldTipoDespesa.getText());
        despesa.setVlrDespesa(Double.parseDouble(jTextFieldValor.getText()));

        despesa.cadastrarDespesa(despesa);
        CarregarTabela();
        LimparjTextField();
    }//GEN-LAST:event_jButtonCadastrarDespesasActionPerformed

    private void jButtonNovaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaDespesaActionPerformed

        HabilitarJTextField();
        DesabilitarJbuttom();
        jButtonCadastrarDespesas.setEnabled(true);
        LimparjTextField();
    }//GEN-LAST:event_jButtonNovaDespesaActionPerformed

    private void LimparjTextField(){
        
        jTextFieldIdConta.setText("");    
        jTextFieldDataPagamento.setText("");        
        jTextFieldDataPagamentoEsperado.setText("");
        jTextFieldTipoDespesa.setText("");
        jTextFieldValor.setText("");
    }
    
    private void CarregarTabela(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableDespesas.getModel();
        tabela.setNumRows(0);
      
        Despesa despesas = new Despesa();
        
        try {
            for(Despesa d: despesas.listarDespesa()){
                tabela.addRow(new Object[]{
                    d.getIdConta(),
                    d.getDataPagto(),
                    d.getDataPagtoEsperado(),
                    d.getTipoDespesa(),
                    d.getVlrDespesa()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela"+erro,
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }
    
    public void DesabilitarJbuttom(){
        jButtonAtualizarDespesas.setEnabled(false);
        jButtonCadastrarDespesas.setEnabled(false);
        jButtonExcluirDespesas.setEnabled(false);
    }
    
    public void DesabilitarJTextField(){
        jTextFieldIdConta.setEnabled(false);
        jTextFieldDataPagamento.setEnabled(false);
        jTextFieldDataPagamentoEsperado.setEnabled(false);
        jTextFieldTipoDespesa.setEnabled(false);
        jTextFieldValor.setEnabled(false);
        
        jLabelIdConta.setEnabled(false);
        jLabelDataPagamento.setEnabled(false);
        jLabelDataPagamentoEsperado.setEnabled(false);
        jLabelTipoDespesa.setEnabled(false);
        jLabelvalor.setEnabled(false);
    }
    
    public void HabilitarJbuttom(){
        jButtonAtualizarDespesas.setEnabled(true);
        jButtonCadastrarDespesas.setEnabled(true);
        jButtonExcluirDespesas.setEnabled(true);
    }
    
    public void HabilitarJTextField(){
        jTextFieldIdConta.setEnabled(true);
        jTextFieldDataPagamento.setEnabled(true);
        jTextFieldDataPagamentoEsperado.setEnabled(true);
        jTextFieldTipoDespesa.setEnabled(true);
        jTextFieldValor.setEnabled(true);
        
        jLabelIdConta.setEnabled(true);
        jLabelDataPagamento.setEnabled(true);
        jLabelDataPagamentoEsperado.setEnabled(true);
        jLabelTipoDespesa.setEnabled(true);
        jLabelvalor.setEnabled(true);
        
    }    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarDespesas;
    private javax.swing.JButton jButtonCadastrarDespesas;
    private javax.swing.JButton jButtonExcluirDespesas;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNovaDespesa;
    private javax.swing.JLabel jLabelDataPagamento;
    private javax.swing.JLabel jLabelDataPagamentoEsperado;
    private javax.swing.JLabel jLabelIdConta;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JLabel jLabelTipoDespesa;
    private javax.swing.JLabel jLabelvalor;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDespesas;
    private javax.swing.JTextField jTextFieldDataPagamento;
    private javax.swing.JTextField jTextFieldDataPagamentoEsperado;
    private javax.swing.JTextField jTextFieldIdConta;
    private javax.swing.JTextField jTextFieldTipoDespesa;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
