/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pubfuture.Despesa;
import pubfuture.Receita;

/**
 *
 * @author ferna
 */
public class CadastroReceitas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroReceitas
     */
    public CadastroReceitas() {
        initComponents();
        CarregarTabela();
        DesabilitarJbuttom();
        DesabilitarJTextField();
        LimparjTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void LimparjTextField(){
        jTextFieldDataRecebimento.setText("");
        jTextFieldDescricaoReceita.setText("");
        jTextFieldIdConta.setText("");
        jTextFieldTipoReceita.setText("");
        jTextFieldVlrValor.setText("");
        jTextFieldsDataRecebimentoEsperado.setText("");
    }
    
    
    public void DesabilitarJbuttom(){
        jButtonAtualizarReceita.setEnabled(false);
        jButtonCadastrarReceita.setEnabled(false);
        jButtonExcluirReceita.setEnabled(false);
    }
    
    public void DesabilitarJTextField(){
        jTextFieldDataRecebimento.setEnabled(false);
        jTextFieldDescricaoReceita.setEnabled(false);
        jTextFieldIdConta.setEnabled(false);
        jTextFieldTipoReceita.setEnabled(false);
        jTextFieldVlrValor.setEnabled(false);
        jTextFieldsDataRecebimentoEsperado.setEnabled(false);
        
        jLabelDataRecebimento.setEnabled(false);
        jLabelDataRecebimentoEsperado.setEnabled(false);
        jLabelDescricaoReceita.setEnabled(false);
        jLabelIdConta.setEnabled(false);
        jLabelTipoReceita.setEnabled(false);
        jLabelVlrReceita.setEnabled(false);        
    }
    
    public void HabilitarJbuttom(){
        jButtonAtualizarReceita.setEnabled(true);
        jButtonCadastrarReceita.setEnabled(true);
        jButtonExcluirReceita.setEnabled(true);
    }
    
    public void HabilitarJTextField(){
        jTextFieldDataRecebimento.setEnabled(true);
        jTextFieldDescricaoReceita.setEnabled(true);
        jTextFieldIdConta.setEnabled(true);
        jTextFieldTipoReceita.setEnabled(true);
        jTextFieldVlrValor.setEnabled(true);
        jTextFieldsDataRecebimentoEsperado.setEnabled(true);
        
        jLabelDataRecebimento.setEnabled(true);
        jLabelDataRecebimentoEsperado.setEnabled(true);
        jLabelDescricaoReceita.setEnabled(true);
        jLabelIdConta.setEnabled(true);
        jLabelTipoReceita.setEnabled(true);
        jLabelVlrReceita.setEnabled(true); 

    }   
    
    private void CarregarTabela(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableReceitas.getModel();
        tabela.setNumRows(0);
      
       Receita receitas = new Receita();
        
        try {
            for(Receita r: receitas.listarReceita()){
                tabela.addRow(new Object[]{
                    r.getIdConta(),
                    r.getTipoReceita(),
                    r.getDataRecebimento(),
                    r.getDataRecebEsperado(),
                    r.getDescReceita(),
                    r.getVlrReceita()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela"+erro,
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastrarReceita = new javax.swing.JButton();
        jButtonExcluirReceita = new javax.swing.JButton();
        jButtonAtualizarReceita = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelIdConta = new javax.swing.JLabel();
        jLabelTipoReceita = new javax.swing.JLabel();
        jLabelDataRecebimento = new javax.swing.JLabel();
        jLabelDataRecebimentoEsperado = new javax.swing.JLabel();
        jLabelDescricaoReceita = new javax.swing.JLabel();
        jLabelVlrReceita = new javax.swing.JLabel();
        jTextFieldIdConta = new javax.swing.JTextField();
        jTextFieldTipoReceita = new javax.swing.JTextField();
        jTextFieldDataRecebimento = new javax.swing.JTextField();
        jTextFieldsDataRecebimentoEsperado = new javax.swing.JTextField();
        jTextFieldDescricaoReceita = new javax.swing.JTextField();
        jTextFieldVlrValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReceitas = new javax.swing.JTable();
        jLabelInstrucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição / Criação de Receitas"));

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/novo.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCadastrarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        jButtonCadastrarReceita.setText("Salvar");
        jButtonCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarReceitaActionPerformed(evt);
            }
        });

        jButtonExcluirReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir.png"))); // NOI18N
        jButtonExcluirReceita.setText("Excluir");
        jButtonExcluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirReceitaActionPerformed(evt);
            }
        });

        jButtonAtualizarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        jButtonAtualizarReceita.setText("Atualizar");
        jButtonAtualizarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarReceitaActionPerformed(evt);
            }
        });

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabelIdConta.setText("Id Conta");

        jLabelTipoReceita.setText("Tipo");

        jLabelDataRecebimento.setText("Recebimento");

        jLabelDataRecebimentoEsperado.setText("Rec Esperado");

        jLabelDescricaoReceita.setText("Descrição");

        jLabelVlrReceita.setText("Valor");

        jTextFieldIdConta.setText("jTextField1");

        jTextFieldTipoReceita.setText("jTextField2");

        jTextFieldDataRecebimento.setText("jTextField3");

        jTextFieldsDataRecebimentoEsperado.setText("jTextField4");

        jTextFieldDescricaoReceita.setText("jTextField5");

        jTextFieldVlrValor.setText("jTextField6");

        jTableReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Conta", "Tipo", "Recebimento", "Rec Esperado", "Descrição", "Valor"
            }
        ));
        jTableReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableReceitas);

        jLabelInstrucao.setForeground(new java.awt.Color(255, 0, 51));
        jLabelInstrucao.setText("*Selecione na tabela abaixo a conta para Exclusão ou Alteração");

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovo)
                            .addComponent(jLabelIdConta)
                            .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCadastrarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTipoReceita)
                            .addComponent(jTextFieldTipoReceita))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonExcluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataRecebimento)
                            .addComponent(jTextFieldDataRecebimento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAtualizarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataRecebimentoEsperado)
                            .addComponent(jTextFieldsDataRecebimentoEsperado))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDescricaoReceita)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDescricaoReceita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBaseLayout.createSequentialGroup()
                                .addComponent(jLabelVlrReceita)
                                .addGap(36, 36, 36))
                            .addComponent(jTextFieldVlrValor)))
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addComponent(jLabelInstrucao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonCadastrarReceita)
                    .addComponent(jButtonExcluirReceita)
                    .addComponent(jButtonAtualizarReceita)
                    .addComponent(jButtonHome))
                .addGap(18, 18, 18)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdConta)
                    .addComponent(jLabelTipoReceita)
                    .addComponent(jLabelDataRecebimento)
                    .addComponent(jLabelDataRecebimentoEsperado)
                    .addComponent(jLabelDescricaoReceita)
                    .addComponent(jLabelVlrReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsDataRecebimentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescricaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVlrValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelInstrucao)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        HabilitarJTextField();
        DesabilitarJbuttom();
        jButtonCadastrarReceita.setEnabled(true);
        LimparjTextField();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarReceitaActionPerformed
               
        Receita receitas = new Receita();
        receitas.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        receitas.setDataRecebEsperado(Date.valueOf(jTextFieldDataRecebimento.getText())); 
        receitas.setDataRecebimento(Date.valueOf(jTextFieldDataRecebimento.getText())); 
        receitas.setTipoReceita(jTextFieldTipoReceita.getText());
        receitas.setDescReceita(jTextFieldDescricaoReceita.getText());        
        receitas.setVlrReceita(Double.parseDouble(jTextFieldVlrValor.getText()));
        
        receitas.cadastrarReceita(receitas);
        CarregarTabela();
        LimparjTextField();
    }//GEN-LAST:event_jButtonCadastrarReceitaActionPerformed

    private void jButtonExcluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirReceitaActionPerformed
        Receita receitas =new Receita();        
        Integer index = jTableReceitas.getSelectedRow();
        receitas = receitas.listarReceita().get(index);
        receitas.removerReceita(Integer.parseInt(jTextFieldIdConta.getText()));
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
        
    }//GEN-LAST:event_jButtonExcluirReceitaActionPerformed

    private void jButtonAtualizarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarReceitaActionPerformed
        
        Receita receitas =new Receita();        
        Integer index = jTableReceitas.getSelectedRow();
        receitas = receitas.listarReceita().get(index);
        receitas.setIdConta(Integer.parseInt(jTextFieldIdConta.getText()));
        receitas.setTipoReceita(jTextFieldTipoReceita.getText());    
        receitas.setDataRecebimento(Date.valueOf(jTextFieldDataRecebimento.getText()));
        receitas.setDataRecebEsperado(Date.valueOf(jTextFieldsDataRecebimentoEsperado.getText()));
        receitas.setDescReceita(jTextFieldDescricaoReceita.getText());          
        receitas.setVlrReceita(Double.parseDouble(jTextFieldVlrValor.getText()));
 
        receitas.editarReceita(receitas);        
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
        
    }//GEN-LAST:event_jButtonAtualizarReceitaActionPerformed

    private void jTableReceitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceitasMouseClicked
        Receita receitas = new Receita();
        Integer index = jTableReceitas.getSelectedRow();
        receitas= receitas.listarReceita().get(index);
        jTextFieldIdConta.setText(String.valueOf(receitas.getIdConta()));
        jTextFieldTipoReceita.setText(receitas.getTipoReceita());
        jTextFieldDataRecebimento.setText(String.valueOf(receitas.getDataRecebimento()));
        jTextFieldsDataRecebimentoEsperado.setText(String.valueOf(receitas.getDataRecebEsperado()));
        jTextFieldDescricaoReceita.setText(receitas.getDescReceita());
        jTextFieldVlrValor.setText(String.valueOf(receitas.getVlrReceita()));
   
        
        jButtonCadastrarReceita.setEnabled(false);
        jButtonAtualizarReceita.setEnabled(true);
        jButtonExcluirReceita.setEnabled(true);
        HabilitarJTextField();
        jLabelIdConta.setEnabled(false);
        jTextFieldIdConta.setEnabled(false);    
        
        
    }//GEN-LAST:event_jTableReceitasMouseClicked

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed

        try {
            Principal telaPrincipal = new Principal();
            telaPrincipal.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        } 
        finally{
        dispose();
        }
       
   
        
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarReceita;
    private javax.swing.JButton jButtonCadastrarReceita;
    private javax.swing.JButton jButtonExcluirReceita;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabelDataRecebimento;
    private javax.swing.JLabel jLabelDataRecebimentoEsperado;
    private javax.swing.JLabel jLabelDescricaoReceita;
    private javax.swing.JLabel jLabelIdConta;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JLabel jLabelTipoReceita;
    private javax.swing.JLabel jLabelVlrReceita;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReceitas;
    private javax.swing.JTextField jTextFieldDataRecebimento;
    private javax.swing.JTextField jTextFieldDescricaoReceita;
    private javax.swing.JTextField jTextFieldIdConta;
    private javax.swing.JTextField jTextFieldTipoReceita;
    private javax.swing.JTextField jTextFieldVlrValor;
    private javax.swing.JTextField jTextFieldsDataRecebimentoEsperado;
    // End of variables declaration//GEN-END:variables
}
