/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import pubfuture.Conta;
import pubfuture.Despesa;
import pubfuture.Receita;

/**
 *
 * @author ferna
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
                
        Receita receitas = new Receita();
        Double totalReceita;
        totalReceita=receitas.listarReceitaTotal();
        jLabelTotalReceitaValor.setText(totalReceita.toString());
        
        Despesa despesas = new Despesa();
        Double totalDespesa;
        totalDespesa=despesas.listarDespesaTotal();
        jLabelTotalDespesaValor.setText(totalDespesa.toString());
        
        Conta contas = new Conta();
        Double totalConta;
        totalConta=contas.listarSaldo();
        jLabelTotalContaValor.setText(totalConta.toString());        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonTelaReceitas = new javax.swing.JButton();
        jButtonTelaDespesas = new javax.swing.JButton();
        jButtonTelaContas = new javax.swing.JButton();
        jPanelResumo = new javax.swing.JPanel();
        jLabelResumoReceita = new javax.swing.JLabel();
        jLabelResumoDespesa = new javax.swing.JLabel();
        jLabelResumoConta = new javax.swing.JLabel();
        jLabelTotalReceitaValor = new javax.swing.JLabel();
        jLabelTotalDespesaValor = new javax.swing.JLabel();
        jLabelTotalContaValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Tela Principal"));

        jButtonTelaReceitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/receita.png"))); // NOI18N
        jButtonTelaReceitas.setText("Receitas");
        jButtonTelaReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaReceitasActionPerformed(evt);
            }
        });

        jButtonTelaDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Despesas.png"))); // NOI18N
        jButtonTelaDespesas.setText("Despesas");
        jButtonTelaDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaDespesasActionPerformed(evt);
            }
        });

        jButtonTelaContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Contas.png"))); // NOI18N
        jButtonTelaContas.setText("Contas");
        jButtonTelaContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaContasActionPerformed(evt);
            }
        });

        jPanelResumo.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));

        jLabelResumoReceita.setText("Total Receitas");

        jLabelResumoDespesa.setText("Total Despesa");

        jLabelResumoConta.setText("Total Contas");

        jLabelTotalReceitaValor.setText("jLabel1");

        jLabelTotalDespesaValor.setText("jLabel1");

        jLabelTotalContaValor.setText("jLabel1");

        javax.swing.GroupLayout jPanelResumoLayout = new javax.swing.GroupLayout(jPanelResumo);
        jPanelResumo.setLayout(jPanelResumoLayout);
        jPanelResumoLayout.setHorizontalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResumoReceita)
                    .addComponent(jLabelResumoDespesa)
                    .addComponent(jLabelResumoConta))
                .addGap(32, 32, 32)
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalContaValor)
                    .addComponent(jLabelTotalDespesaValor)
                    .addComponent(jLabelTotalReceitaValor))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelResumoLayout.setVerticalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResumoReceita)
                    .addComponent(jLabelTotalReceitaValor))
                .addGap(18, 18, 18)
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResumoDespesa)
                    .addComponent(jLabelTotalDespesaValor))
                .addGap(18, 18, 18)
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResumoConta)
                    .addComponent(jLabelTotalContaValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTelaDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTelaReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTelaContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanelResumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addComponent(jButtonTelaReceitas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTelaDespesas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTelaContas))
                    .addComponent(jPanelResumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTelaReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaReceitasActionPerformed

        try {
            CadastroReceitas telaReceitas = new CadastroReceitas();
            telaReceitas.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }         
        finally{
        dispose();
        }        
    }//GEN-LAST:event_jButtonTelaReceitasActionPerformed

    private void jButtonTelaDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaDespesasActionPerformed
        try {
            cadastroDespesa telaDespesa = new cadastroDespesa();
            telaDespesa.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }  
        finally{
        dispose();
        }
        
    }//GEN-LAST:event_jButtonTelaDespesasActionPerformed

    private void jButtonTelaContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaContasActionPerformed

        try {
            CadastroConta telaContas = new CadastroConta();
            telaContas.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }   
        finally{
        dispose();
        }        
        
        
    }//GEN-LAST:event_jButtonTelaContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTelaContas;
    private javax.swing.JButton jButtonTelaDespesas;
    private javax.swing.JButton jButtonTelaReceitas;
    private javax.swing.JLabel jLabelResumoConta;
    private javax.swing.JLabel jLabelResumoDespesa;
    private javax.swing.JLabel jLabelResumoReceita;
    private javax.swing.JLabel jLabelTotalContaValor;
    private javax.swing.JLabel jLabelTotalDespesaValor;
    private javax.swing.JLabel jLabelTotalReceitaValor;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelResumo;
    // End of variables declaration//GEN-END:variables
}
